### ISSUE TITLE
Showing up keyboard through uibutton click?

### ISSUE THREAD

**Issue by zeropt7** [kawanet/KWFontPicker#1]
Hi, thanks a lot for your code. It is amazing.
I wonder how the code should be written if I want to bring up the keyboard through button click, instead of tapping on the uitextview?

Thank you in advance.

**Comment by kawanet** [comment]
Thanks!

[textEditor setEditorMode:KWTextEditorModeKeyboard];

Please set editorMode property to open a keyboard.
Add this at your button click event handler like UIControlEventTouchDown.

@kawanet

**Comment by zeropt7** [comment]
Thanks for your help.
However another problem came up, I wonder if the app can be used in iOS 5? (Except for the problem of autolayout)
I'm having a problem of debugging the app in iOS 5 and the picker changed all to question marks.
Thanks!
![Screen Shot 2013-04-18 at 2 57 17 PM](https://f.cloud.github.com/assets/1882034/395325/1263dd7c-a7f9-11e2-86a4-59bbc646b321.png)

**Comment by kawanet** [comment]
The library uses NSAttributedString which is not supported at iOS5.
I guess there would be some alternative way to do the same thing on iOS5, however.

@kawanet
