### ISSUE TITLE
Broken on iOS 7?

### ISSUE THREAD

**Issue by chintan100** [kawanet/KWFontPicker#4]
The font picker is totally blank when run on iOS 7. When we scroll, we hear the click sounds but it does not show anything on screen. It logs the selected font in "fontPicker setChangeHandler" but there is nothing displayed. 

Please let me know if there are any plans to update this on iOS 7. 

Thanks.

**Comment by kawanet** [comment]
I've confirmed that it's broken on iOS 7 when compiled with Xcode 5. orz.
I'd like to fix it soon. Any hints are welcomed. Thanks!

**Comment by chintan100** [comment]
I tried the solution mentioned here but it does not work in our case: http://stackoverflow.com/questions/18945119/uipickerview-nsattributedstring-not-available-in-ios-7/19103013#19103013

**Comment by kawanet** [comment]
supported: 95fd156100e1fdd68e2a2e909609058f63bd9035

**Comment by chintan100** [comment]
Thank you for your awesome and very fast fix! It works perfectly now!
